# Theme's properties
theme: jekyll-theme-minimal
title: MAITRANGHS's Curriculum Vitae & Portfolio
description: Curriculum Vitae & Portfolio
logo: /assets/img/photo.png
# Customized personal information
email: maitrang88bk@gmail.com
skypeId: maitranghs
cellPhone: (+39) 351-961-0880
address: Trento, Italy