# Theme's properties
theme: jekyll-theme-minimal
title: MAITRANGHS's Curriculum Vitae & Portfolio
description: MAITRANGHS's Curriculum Vitae & Portfolio
logo: /assets/img/photo.png
# Customized personal information
email: maitrang88bk@gmail.com
skypeId: maitranghs
cellPhone: (+39) 351-961-0880
address: Via Dei Masetti 36, 38121, Trento, Province of Trento, Italy